name: Production Deployment

on:
  push:
    branches:
      - production

  pull_request:
    branches: [production]
    types: [opened, synchronize]

jobs:
  production_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build app
        run: npm run build
      - name: E2E on chrome
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          command: npm run cypress:run
          start: npm run preview
          wait-on: http://localhost:3000
